### ISSUE TITLE
TensorFlow 1.15 compatibility

### ISSUE THREAD

**Issue by maziyarpanahi** [dhruvrajan/tensorflow-keras-java#14]
Hi,

Very nice work! Thank you for sharing it. I know TensorFlow hasn't released anything on Maven for TF 2.x, but they have TF 1.15.0 which is compatible with TF V1 and some APIs in V2.

I was wondering if your work is compatible with TF 1.15.0 APIs.

Many thanks

**Comment by dhruvrajan** [comment]
HI @maziyarpanahi ! Apologies I didn't see this earlier.

This repository is compatible with TF1.15, however we're developing this further at `github.com/tensorflow/java`, and the 2.0 releases, when available, will introduce some breaking changes at the core api level.

Feel free to get in touch any time!

**Comment by maziyarpanahi** [comment]
@dhruvrajan Fantastic news! I've been following `github.com/tensorflow/java` and can't wait for the 2.x compatible release for Java. Great work, thanks for replying. 
I'll start using this in TF 1.15.x just to get to know some stuff since I mostly do it in Python and then use the saved_model in Java. 

Best of luck for `github.com/tensorflow/java` and the upcoming Java release for TF 2.x.

**Comment by dhruvrajan** [comment]
Awesome, sounds good! Please let me know if you run into any issues / things that should be added! Of course, all contributions welcome :)
